### ISSUE TITLE
Pip install fails without Cython

### ISSUE THREAD

**Issue by w-bonelli** [simpeg/discretize#282]
Hello, just a note that `Cython` seems to be required for `pip install discretize` to succeed:

```
% pip install discretize 
Collecting discretize
  Using cached discretize-0.8.0.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.8
  Using cached numpy-1.23.0-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
Collecting scipy>=0.13
  Downloading scipy-1.8.1-cp310-cp310-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 MB 33.8 MB/s eta 0:00:00
Using legacy 'setup.py install' for discretize, since package 'wheel' is not installed.
Installing collected packages: numpy, scipy, discretize
  Running setup.py install for discretize ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for discretize did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4t/2sbpjbgs1n73t8s7rx4gb_ph0000gn/T/pip-install-28z8fi_n/discretize_4cc67acdec37434c843753f76a4a1933/setup.py", line 75, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> discretize

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure
```

Happy to add it to `install_requires` if PRs are accepted. Thanks!

**Comment by w-bonelli** [comment]
This was just an env issue. Sorry!
